//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarMate.Resources.Account.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление учетной записью.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить внешнюю учетную запись.
        /// </summary>
        public static string AddNewAccount {
            get {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string ChangingPassword {
            get {
                return ResourceManager.GetString("ChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы прошли проверку через.
        /// </summary>
        public static string CheckSuccess {
            get {
                return ResourceManager.GetString("CheckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и его подтверждение не совпадают.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля обязательное поле.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты обязательное поле.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение {0} должно содержать от {2} до {1} символов.
        /// </summary>
        public static string EmailStringLength {
            get {
                return ResourceManager.GetString("EmailStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный Адрес электронной почты.
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя на этом сайте ниже и нажмите кнопку &quot;Регистрация&quot;, чтобы завершить вход..
        /// </summary>
        public static string EndRegister {
            get {
                return ResourceManager.GetString("EndRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход топлива.
        /// </summary>
        public static string FuelConsumption {
            get {
                return ResourceManager.GetString("FuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свяжите свою учетную запись в.
        /// </summary>
        public static string LinkAaccount {
            get {
                return ResourceManager.GetString("LinkAaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при входе.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин обязательное поле.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение {0} должно содержать от {2} до {1} символов.
        /// </summary>
        public static string LoginStringLength {
            get {
                return ResourceManager.GetString("LoginStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет локального пароля для этого сайта. Добавьте локальный пароль, чтобы входить без внешней учетной записи..
        /// </summary>
        public static string NewPasswordInfo {
            get {
                return ResourceManager.GetString("NewPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль обязательное поле.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль обязательное поле.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль обязательное поле.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение {0} должно содержать от {2} до {1} символов.
        /// </summary>
        public static string PasswordStringLength {
            get {
                return ResourceManager.GetString("PasswordStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированные внешние учетные записи.
        /// </summary>
        public static string RegisteredExternalAccounts {
            get {
                return ResourceManager.GetString("RegisteredExternalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось войти через службу..
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать пароль.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход через другую службу.
        /// </summary>
        public static string SignInWithAnotherService {
            get {
                return ResourceManager.GetString("SignInWithAnotherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единицы расхода топлива.
        /// </summary>
        public static string UnitFuelConsumption {
            get {
                return ResourceManager.GetString("UnitFuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единицы расхода топлива не выбраны.
        /// </summary>
        public static string UnitFuelConsumptionRequired {
            get {
                return ResourceManager.GetString("UnitFuelConsumptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы вошли как.
        /// </summary>
        public static string YouLoggedAs {
            get {
                return ResourceManager.GetString("YouLoggedAs", resourceCulture);
            }
        }
    }
}
