//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarMate.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преимущества сервиса:.
        /// </summary>
        public static string AdvantagesService {
            get {
                return ResourceManager.GetString("AdvantagesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to брендов АЗС.
        /// </summary>
        public static string BrandsAzs {
            get {
                return ResourceManager.GetString("BrandsAzs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии и рейтинг.
        /// </summary>
        public static string CommentsAndRatings {
            get {
                return ResourceManager.GetString("CommentsAndRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение своего авто с другими владельцами такого же авто.
        /// </summary>
        public static string ComparisonCars {
            get {
                return ResourceManager.GetString("ComparisonCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные от других пользователей.
        /// </summary>
        public static string DataFromOtherUsers {
            get {
                return ResourceManager.GetString("DataFromOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет затрат на автомобиль, статистика расходов, сравнение показателей.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображение цен на топливо из разных источников.
        /// </summary>
        public static string DisplayFuelPrices {
            get {
                return ResourceManager.GetString("DisplayFuelPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображение на карте.
        /// </summary>
        public static string DisplayOnMap {
            get {
                return ResourceManager.GetString("DisplayOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распространение данных.
        /// </summary>
        public static string DisseminationData {
            get {
                return ResourceManager.GetString("DisseminationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наполнение данными.
        /// </summary>
        public static string FillingData {
            get {
                return ResourceManager.GetString("FillingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение POI точек и показ на карте.
        /// </summary>
        public static string GettingPoiPoints {
            get {
                return ResourceManager.GetString("GettingPoiPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помогает экономить.
        /// </summary>
        public static string HelpsSaving {
            get {
                return ResourceManager.GetString("HelpsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сколько денег потрачено на содержание автомобиля за текущий год?.
        /// </summary>
        public static string HowMoneySpent {
            get {
                return ResourceManager.GetString("HowMoneySpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как работает?.
        /// </summary>
        public static string HowWork {
            get {
                return ResourceManager.GetString("HowWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to марок автомобилей.
        /// </summary>
        public static string MarkAuto {
            get {
                return ResourceManager.GetString("MarkAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мониторинг цен топлива.
        /// </summary>
        public static string MonitoringFuelPrices {
            get {
                return ResourceManager.GetString("MonitoringFuelPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный профиль.
        /// </summary>
        public static string PersonalProfile {
            get {
                return ResourceManager.GetString("PersonalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирование и составление графика будущего тех обслуживания.
        /// </summary>
        public static string PlanningService {
            get {
                return ResourceManager.GetString("PlanningService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставление информации о других авто.
        /// </summary>
        public static string ProvidingInformationAboutOtherCars {
            get {
                return ResourceManager.GetString("ProvidingInformationAboutOtherCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запоминание событий связанных с автомобилем и ведение статистики.
        /// </summary>
        public static string RememberEvents {
            get {
                return ResourceManager.GetString("RememberEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных.
        /// </summary>
        public static string RetrievingData {
            get {
                return ResourceManager.GetString("RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экономия!.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает местоположение.
        /// </summary>
        public static string ShowLocation {
            get {
                return ResourceManager.GetString("ShowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает цену.
        /// </summary>
        public static string ShowPrice {
            get {
                return ResourceManager.GetString("ShowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраняются события.
        /// </summary>
        public static string StoredEvents {
            get {
                return ResourceManager.GetString("StoredEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarMate мониторинг цен топлива, бортовой журнал.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какие проблемы мы решаем?.
        /// </summary>
        public static string WhatProblemsWeSolve {
            get {
                return ResourceManager.GetString("WhatProblemsWeSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда нужно сделать ТО или поменять масло и другие расходники?.
        /// </summary>
        public static string WhenNeedMaintenance {
            get {
                return ResourceManager.GetString("WhenNeedMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где находиться нужная сеть АЗС?.
        /// </summary>
        public static string WhereDesiredNetworkGasStations {
            get {
                return ResourceManager.GetString("WhereDesiredNetworkGasStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где заправиться дешевле и нужным топливом?.
        /// </summary>
        public static string WhereRefuelCheaperAndFuelFit {
            get {
                return ResourceManager.GetString("WhereRefuelCheaperAndFuelFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачем это?.
        /// </summary>
        public static string WhyIsThis {
            get {
                return ResourceManager.GetString("WhyIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если водитель хочет экономить, мы предоставляем ему инструмент «Веб приложение» и «Длинные руки» в виде мобильного приложения. К этому пользователь добавляет свою мотивацию и в итоге получается ожидаемый результат – экономия..
        /// </summary>
        public static string WhyIsThisAnswer {
            get {
                return ResourceManager.GetString("WhyIsThisAnswer", resourceCulture);
            }
        }
    }
}
