//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Car {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Car() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarMate.Resources.Car.Car", typeof(Car).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все транспортные средства.
        /// </summary>
        public static string AllVehicles {
            get {
                return ResourceManager.GetString("AllVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография автомобиля.
        /// </summary>
        public static string CarPhoto {
            get {
                return ResourceManager.GetString("CarPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коробка передач.
        /// </summary>
        public static string CarTransmission {
            get {
                return ResourceManager.GetString("CarTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий/отзыв.
        /// </summary>
        public static string CommentOrReview {
            get {
                return ResourceManager.GetString("CommentOrReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход топлива.
        /// </summary>
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание транспортного средства.
        /// </summary>
        public static string CreateVehicle {
            get {
                return ResourceManager.GetString("CreateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата покупки.
        /// </summary>
        public static string DateBuy {
            get {
                return ResourceManager.GetString("DateBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление транспортного средства.
        /// </summary>
        public static string DeleteVehicle {
            get {
                return ResourceManager.GetString("DeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование транспортного средства.
        /// </summary>
        public static string EditingVehicle {
            get {
                return ResourceManager.GetString("EditingVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год выпуска.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модификация.
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string Odometr {
            get {
                return ResourceManager.GetString("Odometr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпочитаемый тип топлива.
        /// </summary>
        public static string PreferredTypeFuel {
            get {
                return ResourceManager.GetString("PreferredTypeFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть все фото.
        /// </summary>
        public static string SeeAllPhotos {
            get {
                return ResourceManager.GetString("SeeAllPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -выберите марку-.
        /// </summary>
        public static string SelectBrand {
            get {
                return ResourceManager.GetString("SelectBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -выберите модель-.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -выберите модификацию-.
        /// </summary>
        public static string SelectModification {
            get {
                return ResourceManager.GetString("SelectModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -выберите тип топлива-.
        /// </summary>
        public static string SelectTypeFuel {
            get {
                return ResourceManager.GetString("SelectTypeFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -выберите тип коробки передач-.
        /// </summary>
        public static string SelectTypeTransmission {
            get {
                return ResourceManager.GetString("SelectTypeTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объем бака.
        /// </summary>
        public static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка пользователя.
        /// </summary>
        public static string UserRating {
            get {
                return ResourceManager.GetString("UserRating", resourceCulture);
            }
        }
    }
}
