//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEvents
    {
        public CarEvents()
        {
            this.LogBook = new HashSet<LogBook>();
        }
    
        public int Id { get; set; }
        public int CarId { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<int> FuelCategoryId { get; set; }
        public Nullable<int> Odometer { get; set; }
        public double CostTotal { get; set; }
        public System.DateTime DateEvent { get; set; }
        public string Comment { get; set; }
        public Nullable<double> FuelCount { get; set; }
        public Nullable<double> PricePerLitr { get; set; }
        public Nullable<double> Latitute { get; set; }
        public Nullable<double> Longitute { get; set; }
        public bool IsFullTank { get; set; }
        public bool IsMissedFilling { get; set; }
        public string NameEvent { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int State { get; set; }
    
        public virtual EventTypes EventTypes { get; set; }
        public virtual FuelCategories FuelCategories { get; set; }
        public virtual Cars Cars { get; set; }
        public virtual ICollection<LogBook> LogBook { get; set; }
    }
}
