//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.FuelCategories = new HashSet<FuelCategories>();
            this.Placemarks = new HashSet<Placemarks>();
            this.Regions = new HashSet<Regions>();
            this.Vendors = new HashSet<Vendors>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<FuelCategories> FuelCategories { get; set; }
        public virtual ICollection<Placemarks> Placemarks { get; set; }
        public virtual ICollection<Regions> Regions { get; set; }
        public virtual ICollection<Vendors> Vendors { get; set; }
    }
}
