//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placemarks
    {
        public Placemarks()
        {
            this.Prices = new HashSet<Prices>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int State { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
