//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regions
    {
        public Regions()
        {
            this.Placemarks = new HashSet<Placemarks>();
            this.Prices = new HashSet<Prices>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public string Region { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int State { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Placemarks> Placemarks { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
