//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitFuelConsumption
    {
        public UnitFuelConsumption()
        {
            this.UnitDistance = new HashSet<UnitDistance>();
            this.UnitVolume = new HashSet<UnitVolume>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string NameUnit { get; set; }
        public double Correction { get; set; }
    
        public virtual ICollection<UnitDistance> UnitDistance { get; set; }
        public virtual ICollection<UnitVolume> UnitVolume { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
