//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitVolume
    {
        public UnitVolume()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string NameUnit { get; set; }
        public double Correction { get; set; }
        public int UnitFuelConsumptionId { get; set; }
    
        public virtual UnitFuelConsumption UnitFuelConsumption { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
