//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aliases
    {
        public Aliases()
        {
            this.VendorAliases = new HashSet<VendorAliases>();
        }
    
        public int Id { get; set; }
        public string Alias { get; set; }
    
        public virtual ICollection<VendorAliases> VendorAliases { get; set; }
    }
}
