//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarBrands
    {
        public CarBrands()
        {
            this.CarModels = new HashSet<CarModels>();
        }
    
        public int id { get; set; }
        public int carTypeId { get; set; }
        public string brand { get; set; }
    
        public virtual CarTypes CarTypes { get; set; }
        public virtual ICollection<CarModels> CarModels { get; set; }
    }
}
