//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetails
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public int CarNodeId { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual CarNode CarNode { get; set; }
    }
}
