//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModifications
    {
        public CarModifications()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int id { get; set; }
        public int modelId { get; set; }
        public string modification { get; set; }
        public string horsePower { get; set; }
        public string yearBegin { get; set; }
        public string yearEnd { get; set; }
    
        public virtual CarModels CarModels { get; set; }
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
