//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTypes
    {
        public CarTypes()
        {
            this.CarBrands = new HashSet<CarBrands>();
        }
    
        public int Id { get; set; }
        public string CarType { get; set; }
    
        public virtual ICollection<CarBrands> CarBrands { get; set; }
    }
}
