//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Placemarks = new HashSet<Placemarks>();
        }
    
        public int id { get; set; }
        public string category { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int state { get; set; }
    
        public virtual ICollection<Placemarks> Placemarks { get; set; }
    }
}
