//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTypes
    {
        public EventTypes()
        {
            this.CarEvents = new HashSet<CarEvents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LanguageId { get; set; }
    
        public virtual ICollection<CarEvents> CarEvents { get; set; }
    }
}
