//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelCategories
    {
        public FuelCategories()
        {
            this.CarEvents = new HashSet<CarEvents>();
            this.Prices = new HashSet<Prices>();
        }
    
        public int id { get; set; }
        public int countryId { get; set; }
        public string category { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int state { get; set; }
    
        public virtual ICollection<CarEvents> CarEvents { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
    }
}
