//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public Languages()
        {
            this.Users = new HashSet<Users>();
            this.CarTransmissionLang = new HashSet<CarTransmissionLang>();
            this.UnitDistanceLang = new HashSet<UnitDistanceLang>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<CarTransmissionLang> CarTransmissionLang { get; set; }
        public virtual ICollection<UnitDistanceLang> UnitDistanceLang { get; set; }
    }
}
