//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBook
    {
        public int id { get; set; }
        public int categoryid { get; set; }
        public int chargingid { get; set; }
        public int carId { get; set; }
        public Nullable<float> total_cost { get; set; }
        public Nullable<System.DateTime> dateCharging { get; set; }
    
        public virtual CarEvents CarEvents { get; set; }
        public virtual Cars Cars { get; set; }
        public virtual CategoryLog CategoryLog { get; set; }
    }
}
