//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placemarks
    {
        public Placemarks()
        {
            this.Prices = new HashSet<Prices>();
        }
    
        public int id { get; set; }
        public int countryId { get; set; }
        public Nullable<int> regionId { get; set; }
        public int categoryId { get; set; }
        public Nullable<int> vendorId { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string description { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int state { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
