//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public int PlacemarkId { get; set; }
        public int VendorId { get; set; }
        public int RegionId { get; set; }
        public int FuelId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> UserPrice { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int State { get; set; }
    
        public virtual FuelCategories FuelCategories { get; set; }
        public virtual Placemarks Placemarks { get; set; }
        public virtual Vendors Vendors { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
