//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int id { get; set; }
        public int placemarkid { get; set; }
        public int vendorId { get; set; }
        public int regionId { get; set; }
        public int fuelId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> userPrice { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int state { get; set; }
    
        public virtual FuelCategories FuelCategories { get; set; }
        public virtual Placemarks Placemarks { get; set; }
        public virtual Vendors Vendors { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
