//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitDistanceLang
    {
        public int Id { get; set; }
        public int UnitDistanceId { get; set; }
        public int LanguageId { get; set; }
        public string NameUnit { get; set; }
        public string Comment { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual UnitDistance UnitDistance { get; set; }
    }
}
