//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CarEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarMate.Resources.CarEvents.CarEvents", typeof(CarEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить событие.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все события.
        /// </summary>
        public static string AllEvents {
            get {
                return ResourceManager.GetString("AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За выбранный период нет данных.
        /// </summary>
        public static string CarEventsEmpty {
            get {
                return ResourceManager.GetString("CarEventsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание события.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление события.
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить событие.
        /// </summary>
        public static string DeleteEventAnswer {
            get {
                return ResourceManager.GetString("DeleteEventAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробно.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование события.
        /// </summary>
        public static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заправка.
        /// </summary>
        public static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залито топлива.
        /// </summary>
        public static string FuelCount {
            get {
                return ResourceManager.GetString("FuelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип топлива.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный бак.
        /// </summary>
        public static string FullTank {
            get {
                return ResourceManager.GetString("FullTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустил заправку.
        /// </summary>
        public static string MissedFilling {
            get {
                return ResourceManager.GetString("MissedFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string NameEvent {
            get {
                return ResourceManager.GetString("NameEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Одометр обязательно для заполнения.
        /// </summary>
        public static string OdometerRequired {
            get {
                return ResourceManager.GetString("OdometerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена за .
        /// </summary>
        public static string PricePerLitr {
            get {
                return ResourceManager.GetString("PricePerLitr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонт.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
    }
}
